language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
install: 
  - pip install -r pip_requirements.txt
  - git clone https://github.com/AutomatedTester/browsermob-proxy-py.git
  - mv browsermob-proxy-py/browsermobproxy Pallas/ 
script:
  - py.test --cov-report term-missing --cov Pallas Pallas
after_success: coveralls
