language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install: 
  - pip install -r pip_requirements.txt
  - git clone https://github.com/AutomatedTester/browsermob-proxy-py.git
  - python browsermob-proxy-py/setup.py install
script:
  - py.test --cov-report term-missing --cov Pallas Pallas
after_success: coveralls
